name: Sitemap Build

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.12'
      
      - name: Build Sitemap
        run: python sitemap_builder.py
        
      - name: Commit & Push Sitemap
        run: |
          git config --global user.name 'n3rdium'
          git config --global user.email 'n3rdium@users.noreply.github.com'
          git commit -am "Automated Sitemap Build"
          git push
